[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Variáveis de ambiente de build
# IMPORTANTE: Você precisa adicionar VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY
# nas configurações do site no Netlify (Site settings > Environment variables)

