[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Desabilitar o scanner de secrets para variáveis de ambiente conhecidas
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# As variáveis de ambiente devem ser configuradas no painel do Netlify:
# Site settings > Environment variables > Add a variable
# 
# Adicione estas variáveis:
# - VITE_SUPABASE_URL
# - VITE_SUPABASE_ANON_KEY
# - VITE_GROQ_API_KEY (opcional, para o assistente AI)

